"""
Interview Agent Schemas — Data models for the skill verification interview.

These schemas define the structure of:
- Interview questions (MCQ and written)
- User answers
- LLM evaluations
- Score adjustments

INTERVIEW DESIGN PHILOSOPHY:
    - 7 questions total: 2 verification (MCQ) + 5 assessment (written)
    - Each question tests 2-3 related skills simultaneously
    - Verification questions target HIGH proof score skills (catch bluffers)
    - Assessment questions target LOW proof score skills (discover hidden talent)
    - Penalties are gentle — one question can't prove or disprove a skill entirely
"""

from typing import Dict, List, Optional, Literal
from pydantic import BaseModel, Field


class InterviewQuestion(BaseModel):
    """A single interview question generated by the LLM."""
    
    question_id: int = Field(description="Sequential ID starting from 1")
    question_text: str = Field(description="The actual question to ask")
    question_type: Literal["mcq", "written"] = Field(
        description="MCQ for verification (high score), written for assessment (low score)"
    )
    difficulty: Literal["verification", "assessment"] = Field(
        description="verification = testing high-score claims, assessment = testing low-score potential"
    )
    target_skills: List[str] = Field(
        description="The 2-3 skills this question is designed to test"
    )
    options: Optional[List[str]] = Field(
        None, description="MCQ options (A through D). Only for mcq type."
    )
    correct_option_index: Optional[int] = Field(
        None, description="Index of the correct option (0-3). Only for mcq type."
    )


class InterviewAnswer(BaseModel):
    """A user's answer to one interview question."""
    
    question_id: int
    user_answer: str = Field(description="What the user typed")
    target_skills: List[str] = Field(description="Skills this question was testing")
    question_type: str = Field(description="mcq or written")
    difficulty: str = Field(description="verification or assessment")


class SkillScoreAdjustment(BaseModel):
    """How a single skill's proof score changes after the interview."""
    
    skill_name: str
    original_score: float = Field(ge=0.0, le=1.0)
    demonstrated_knowledge: float = Field(
        ge=0.0, le=1.0,
        description="How well the user demonstrated this skill (from LLM evaluation)"
    )
    adjustment: float = Field(
        description="Score change: positive = boost, negative = penalty, 0 = unchanged"
    )
    new_score: float = Field(ge=0.0, le=1.0)
    reason: str = Field(description="Why the score changed or didn't")


class QuestionEvaluation(BaseModel):
    """LLM's evaluation of one question-answer pair."""
    
    question_id: int
    answer_quality: float = Field(
        ge=0.0, le=1.0,
        description="Overall answer quality: 1.0=perfect, 0.7=good, 0.4=partial, 0.0=wrong"
    )
    feedback: str = Field(description="Brief constructive feedback for the user")
    skill_scores: Dict[str, float] = Field(
        description="Per-skill knowledge demonstration: skill_name -> 0.0 to 1.0"
    )


class InterviewSummary(BaseModel):
    """Summary of the entire interview results."""
    
    total_questions: int
    questions_answered: int
    average_answer_quality: float
    skills_boosted: int = Field(description="How many skills got a score increase")
    skills_penalized: int = Field(description="How many skills got a score decrease")
    skills_unchanged: int = Field(description="How many skills stayed the same")
    adjustments: List[SkillScoreAdjustment] = Field(
        description="All score changes, sorted by absolute change descending"
    )
